# Import some libraries

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df_user=pd.read_csv('BX-Users.csv', encoding='latin-1')

C:\Users\jahna\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


This is the user dataset. Like user id, location ...

In [3]:
df_user.head()        # To show first 5 rows

user_id                            Location   Age
0       1                  nyc, new york, usa   NaN
1       2           stockton, california, usa  18.0
2       3     moscow, yukon territory, russia   NaN
3       4           porto, v.n.gaia, portugal  17.0
4       5  farnborough, hants, united kingdom   NaN

# Clean up null values

In [4]:
df_user.isnull().sum()         # checking the null values 

user_id          0
Location         1
Age         110763
dtype: int64

In [5]:
df_user['Age'].fillna(df_user['Age'].mean(), inplace=True)

In [6]:
df_user.isnull().sum()

user_id     0
Location    1
Age         0
dtype: int64

In [7]:
df_user['Location'].fillna('NA', inplace=True)

In [8]:
df_user.isnull().sum()

user_id     0
Location    0
Age         0
dtype: int64

# Read the books data and Explore

In [9]:
df_books=pd.read_csv('BX-Books.csv', encoding='latin-1')

C:\Users\jahna\anaconda3\lib\site-packages\IPython\core\interactiveshell.py:3444: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  exec(code_obj, self.user_global_ns, self.user_ns)


In [10]:
df_books.head()

isbn                                         book_title  \
0  195153448                                Classical Mythology   
1    2005018                                       Clara Callan   
2   60973129                               Decision in Normandy   
3  374157065  Flu: The Story of the Great Influenza Pandemic...   
4  393045218                             The Mummies of Urumchi   

            book_author year_of_publication                   publisher  
0    Mark P. O. Morford                2002     Oxford University Press  
1  Richard Bruce Wright                2001       HarperFlamingo Canada  
2          Carlo D'Este                1991             HarperPerennial  
3      Gina Bari Kolata                1999        Farrar Straus Giroux  
4       E. J. W. Barber                1999  W. W. Norton &amp; Company

In [11]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            1
year_of_publication    0
publisher              2
dtype: int64

In [12]:
df_books.dropna(inplace=True)

In [13]:
df_books.isnull().sum()

isbn                   0
book_title             0
book_author            0
year_of_publication    0
publisher              0
dtype: int64

# Now, read the data where ratings are given by users.

You will read only first 10k rows otherwise.
Out of memory will occure

In [14]:
df_ratings=pd.read_csv('BX-Book-Ratings.csv', encoding='latin-1', nrows=10000)

In [15]:
df_ratings.head()

user_id        isbn  rating
0   276725  034545104X       0
1   276726   155061224       5
2   276727   446520802       0
3   276729  052165615X       3
4   276729   521795028       6

In [16]:
df_ratings.describe()

user_id        rating
count   10000.000000  10000.000000
mean   265844.379600      1.974700
std     56937.189618      3.424884
min         2.000000      0.000000
25%    277478.000000      0.000000
50%    278418.000000      0.000000
75%    278418.000000      4.000000
max    278854.000000     10.000000

In [17]:
df_ratings.isnull().sum()

user_id    0
isbn       0
rating     0
dtype: int64

 Now merge the dataframes for all practical purpose. User master data is not required. So ignore dataframe df_user

In [18]:
df=pd.merge(df_ratings,df_books, on='isbn')

In [19]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  
0                2002            Ballantine Books  
1                2001                      Heinle  
2                1996                Warner Books  
3                1996                Warner Books  
4                1999  Cambridge University Press

# Now , let's take a quick look at the number of unique users and books

In [20]:
n_users=df['user_id'].nunique()
n_books=df['isbn'].nunique()

In [21]:
print("Number of users :" +str(n_users))
print("Number of Books :" +str(n_books))

Number of users :828
Number of Books :8051


# Convert ISBN variable to numeric numbers in the correct order

In [22]:
df.dtypes

user_id                 int64
isbn                   object
rating                  int64
book_title             object
book_author            object
year_of_publication    object
publisher              object
dtype: object

In [23]:
isbn_list = df.isbn.unique()
print(" Length of isbn List:", len(isbn_list))

 Length of isbn List: 8051


In [24]:
def get_isbn_numeric_id(isbn):
    #print ("  isbn is:" , isbn)
    itemindex = np.where(isbn_list==isbn)
    return itemindex[0][0]

In [25]:
df['isbn_id'] = df['isbn'].apply(get_isbn_numeric_id)

In [26]:
df.head(20)

user_id        isbn  rating  \
0    276725  034545104X       0   
1    276726   155061224       5   
2    276727   446520802       0   
3    278418   446520802       0   
4    276729  052165615X       3   
5    276729   521795028       6   
6    276733  2080674722       0   
7    276744  038550120X       7   
8    278418  038550120X       0   
9    276746   425115801       0   
10   277427   425115801       0   
11   276746   449006522       0   
12   278026   449006522       8   
13   276746   553561618       0   
14   276746  055356451X       0   
15   278418  055356451X       0   
16   276746   786013990       0   
17   276746   786014512       0   
18   276747    60517794       9   
19   278843    60517794       7   

                                           book_title         book_author  \
0                                Flesh Tones: A Novel          M. J. Rose   
1                                    Rites of Passage          Judith Rae   
2                                        The Notebook     Nicholas Sparks   
3                                        The Notebook     Nicholas Sparks   
4                                      Help!: Level 1       Philip Prowse   
5   The Amsterdam Connection : Level 4 (Cambridge ...         Sue Leather   
6                         Les Particules Elementaires  Michel Houellebecq   
7                                     A Painted House        JOHN GRISHAM   
8                                     A Painted House        JOHN GRISHAM   
9                                           Lightning      Dean R. Koontz   
10                                          Lightning      Dean R. Koontz   
11                                Manhattan Hunt Club           JOHN SAUL   
12                                Manhattan Hunt Club           JOHN SAUL   
13                                      Dark Paradise           TAMI HOAG   
14                                         Night Sins           TAMI HOAG   
15                                         Night Sins           TAMI HOAG   
16                                        At the Edge           David Dun   
17                                      Make Them Cry       Kevin O'Brien   
18                           Little Altars Everywhere       Rebecca Wells   
19                           Little Altars Everywhere       Rebecca Wells   

   year_of_publication                   publisher  isbn_id  
0                 2002            Ballantine Books        0  
1                 2001                      Heinle        1  
2                 1996                Warner Books        2  
3                 1996                Warner Books        2  
4                 1999  Cambridge University Press        3  
5                 2001  Cambridge University Press        4  
6                 1998                  Flammarion        5  
7                 2001                   Doubleday        6  
8                 2001                   Doubleday        6  
9                 1996    Berkley Publishing Group        7  
10                1996    Berkley Publishing Group        7  
11                2002            Ballantine Books        8  
12                2002            Ballantine Books        8  
13                1994                      Bantam        9  
14                1995                      Bantam       10  
15                1995                      Bantam       10  
16                2002              Pinnacle Books       11  
17                2002              Pinnacle Books       12  
18                2003                 HarperTorch       13  
19                2003                 HarperTorch       13

# converting both user_id and isbn to ordered list i.e. from 0.. n-1

In [27]:
userid_list = df.user_id.unique()
print(" Length of user_id List:", len(userid_list))

 Length of user_id List: 828


In [28]:
def get_user_id_numeric_id(user_id):
   
    itemindex = np.where(userid_list==user_id)
    return itemindex[0][0]

In [29]:
df['user_id_order'] = df['user_id'].apply(get_user_id_numeric_id)

In [30]:
df.head()

user_id        isbn  rating            book_title      book_author  \
0   276725  034545104X       0  Flesh Tones: A Novel       M. J. Rose   
1   276726   155061224       5      Rites of Passage       Judith Rae   
2   276727   446520802       0          The Notebook  Nicholas Sparks   
3   278418   446520802       0          The Notebook  Nicholas Sparks   
4   276729  052165615X       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher  isbn_id  user_id_order  
0                2002            Ballantine Books        0              0  
1                2001                      Heinle        1              1  
2                1996                Warner Books        2              2  
3                1996                Warner Books        2              3  
4                1999  Cambridge University Press        3              4

# reindex the columns to build matrix

In [31]:
new_col_order= ['user_id_order', 'isbn_id', 'rating', 'book_title', 'book_author','year_of_publication','publisher','isbn','user_id']
df=df.reindex(columns=new_col_order)
df.head()

user_id_order  isbn_id  rating            book_title      book_author  \
0              0        0       0  Flesh Tones: A Novel       M. J. Rose   
1              1        1       5      Rites of Passage       Judith Rae   
2              2        2       0          The Notebook  Nicholas Sparks   
3              3        2       0          The Notebook  Nicholas Sparks   
4              4        3       3        Help!: Level 1    Philip Prowse   

  year_of_publication                   publisher        isbn  user_id  
0                2002            Ballantine Books  034545104X   276725  
1                2001                      Heinle   155061224   276726  
2                1996                Warner Books   446520802   276727  
3                1996                Warner Books   446520802   278418  
4                1999  Cambridge University Press  052165615X   276729

In [32]:
df.tail()

user_id_order  isbn_id  rating                book_title  \
8696             96     8046       7        A Map of the World   
8697             96     8047       0    The Accidental Tourist   
8698             96     8048       0     If Morning Ever Comes   
8699             96     8049       9        Unnatural Exposure   
8700             96     8050       0  Only Love (Magical Love)   

                    book_author year_of_publication                 publisher  \
8696              Jane Hamilton                1999    Anchor Books/Doubleday   
8697                 Anne Tyler                1994  Berkley Publishing Group   
8698                 Anne Tyler                1983  Berkley Publishing Group   
8699  Patricia Daniels Cornwell                1998  Berkley Publishing Group   
8700                Erich Segal                1998  Berkley Publishing Group   

           isbn  user_id  
8696  385720106      243  
8697  425092917      243  
8698  425098834      243  
8699  425163407      243  
8700  425164403      243

In [33]:
df['user_id_order'].nunique()

828

# split the data into training and testing

In [34]:
from sklearn.model_selection import train_test_split
train_data, test_data = train_test_split(df, test_size=0.30)

In [35]:
train_data.shape

(6090, 9)

In [36]:
test_data.shape

(2611, 9)

# Make predictions based on user and item variables

In [37]:
#Create two user-book matrices, one for training and another for testing
train_data_matrix = np.zeros((n_users, n_books))
for line in train_data.itertuples():
    train_data_matrix[line[1]-1, line[2]-1] = line[3] 
    

In [38]:
train_data_matrix

array([[5., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [39]:
test_data_matrix = np.zeros((n_users, n_books))
for line in test_data.itertuples():
    test_data_matrix[line[1]-1, line[2]-1] = line[3] 
    
        

In [40]:
test_data_matrix

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [41]:
from sklearn.metrics.pairwise import pairwise_distances
user_similarity=pairwise_distances(train_data_matrix, metric='cosine')
item_similarity=pairwise_distances(train_data_matrix.T, metric='cosine')

In [42]:
user_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [43]:
item_similarity

array([[0., 1., 1., ..., 1., 1., 1.],
       [1., 0., 1., ..., 1., 1., 1.],
       [1., 1., 0., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 0., 1., 1.],
       [1., 1., 1., ..., 1., 0., 1.],
       [1., 1., 1., ..., 1., 1., 0.]])

In [44]:
def predict(ratings, similarity, type='user'):
    if type =='user':
        mean_user_rating = ratings.mean(axis=1)
        # you use np.newaxis so that mean_user_rating has some format as ratings
        ratings_diff = (ratings-mean_user_rating[:,np.newaxis])
        pred = mean_user_rating[:, np.newaxis] + similarity.dot(ratings_diff)/np.array([np.abs(similarity).sum(axis=1)]).T
        
    elif type == 'item':
        pred= ratings.dot(similarity) / np.array([np.abs(similarity).sum(axis=1)])
    return pred

In [45]:
item_prediction = predict(train_data_matrix, item_similarity, type='item')
user_prediction = predict(train_data_matrix, user_similarity, type='user')

In [46]:
item_prediction


array([[0.        , 0.00062112, 0.00062112, ..., 0.00062161, 0.00062112,
        0.00062112],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.05689441, 0.05689441, 0.05689441, ..., 0.05693978, 0.05689441,
        0.05689441],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [47]:
user_prediction

array([[-0.00116804, -0.00116804,  0.00245953, ...,  0.00971467,
        -0.00116804, -0.00116804],
       [ 0.00425612, -0.00178983,  0.00183774, ...,  0.00909288,
        -0.00178983, -0.00178983],
       [ 0.06121395,  0.05516713,  0.05879522, ...,  0.06605141,
         0.05516713,  0.05516713],
       ...,
       [ 0.00425612, -0.00178983,  0.00183774, ...,  0.00909288,
        -0.00178983, -0.00178983],
       [ 0.00425612, -0.00178983,  0.00183774, ...,  0.00909288,
        -0.00178983, -0.00178983],
       [ 0.00425612, -0.00178983,  0.00183774, ...,  0.00909288,
        -0.00178983, -0.00178983]])

In [48]:
from sklearn.metrics import mean_squared_error
from math import sqrt
def rmse(prediction, ground_truth):
    prediction = prediction[ground_truth.nonzero()].flatten()
    ground_truth = ground_truth[ground_truth.nonzero()].flatten()
    return sqrt(mean_squared_error(prediction, ground_truth))

In [49]:
print('User-based CF RMSE :' + str(rmse(user_prediction, test_data_matrix)))
print('Item-based CF RMSE :' + str(rmse(item_prediction, test_data_matrix)))

User-based CF RMSE :7.644666353971443
Item-based CF RMSE :7.643940173283007
